default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: e_com_development

test:
  <<: *default
  database: e_com_test

production:
  primary_production: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  <<: *primary_production

  cache:
    <<: *primary_production

  queue:
    <<: *primary_production

  cable:
    <<: *primary_production

